spring :  
  profiles:
    active: pro       
  mvc: 
    throw-exception-if-no-handler-found : true 
                  
  datasource:
      url : jdbc:mysql://127.0.0.1:3306/app_db?useUnicode=true&characterEncoding=utf8&useSSL=false
      username : root
      password : root
      driver-class-name: com.mysql.jdbc.Driver 
         
  http:
    encoding:
      charset: UTF-8
    multipart:
     maxFileSize: 50Mb
     maxRequestSize: 100Mb 

#mybatis配置       
mybatis-plus: 
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package : com.app.view.pojo
     
logging:
   level:
       com.app.view.mapper: DEBUG   
       
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql     
         
server : 
  port : 7001 
  tomcat: 
   uri-encoding: UTF-8 
