spring :       
  mvc: 
    throw-exception-if-no-handler-found : true 
                 
  datasource:
      url : jdbc:mysql://127.0.0.1:3306/app_db?useUnicode=true&characterEncoding=utf8&useSSL=false
      username : root
      password : root
      driver-class-name: com.mysql.jdbc.Driver 
         
  http:
    multipart:
     maxFileSize: 50Mb
     maxRequestSize: 100Mb 

#mybatis配置
mybatis: 
  mapperLocations: classpath:mapper/*Mapper.xml
  typeAliasesPackage : com.app.view.pojo
  
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql    
  
 #存放路径
realpath: c:/file/
ip: 101.132.170.212
         
server : 
  port : 7001 
  tomcat: 
   uri-encoding: UTF-8 
