spring :       
  mvc: 
    throw-exception-if-no-handler-found : true 
                 
  datasource:
      url : jdbc:mysql://localhost:3306/app_db?useUnicode=true&characterEncoding=utf8
      username : root
      password : root
      driver-class-name: com.mysql.jdbc.Driver    


#mybatis配置
mybatis: 
  mapperLocations: classpath:mapper/*Mapper.xml
  typeAliasesPackage : com.app.view.pojo
    
      
server : 
  port : 80 
  tomcat: 
   uri-encoding: UTF-8 
